CREATE TABLE TA_COMPANIA(
    ID_COMPANIA    NUMBER,
    NOMBRE         VARCHAR(100),
    APELLIDO       VARCHAR(100),
    NUM_EMPLEADO   NUMBER,
    RFC            VARCHAR(100),
    COMPANIA       VARCHAR(100),
    NOTA           CLOB,
    TRIMESTRE      NUMBER,
    CONSTRAINT     PK_COMPANIA
    PRIMARY KEY    (ID_COMPANIA),
    CONSTRAINT     UK_NUM_EMPLEADO
    UNIQUE         (NUM_EMPLEADO)
);