CREATE TABLE TA_DOCUMENTO(
    ID_DOCUMENTO NUMBER,
    NOMBRE       VARCHAR(100),
    APELLIDO     VARCHAR(100),
    DOCUMENTO    CLOB,
    CORREO       VARCHAR(100),
    STATUS       NUMBER,
    NUM_EMPLEADO NUMBER,
    CONSTRAINT   PK_DOCUMENTO 
    PRIMARY KEY  (ID_DOCUMENTO),
    CONSTRAINT   UK_DOC_NUM_EMPLEADO
    UNIQUE       (NUM_EMPLEADO)
);
