CREATE TABLE TA_USUARIOS(
    ID_USUARIO NUMBER,
    USUARIO NVARCHAR2(100),
    CONTRASENA NVARCHAR2(100),
    ROL NVARCHAR2(100),
    CONSTRAINT PK_USUARIO
    PRIMARY KEY(ID_USUARIO)
);

CREATE INDEX UK_USUARIO
ON TA_USUARIOS (UPPER(USUARIO));