CREATE OR REPLACE PACKAGE PA_COMPANIA AS
    PROCEDURE SP_GETCOMPANIA(
        REC_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_SETCOMPANIA(        
        PA_NOMBRE      IN VARCHAR2,
        PA_APELLIDO    IN VARCHAR2,
        PA_RFC         IN VARCHAR2,
        PA_EMPRESA     IN VARCHAR2,
        PA_NOTA        IN CLOB,
        PA_TRIMESTRE   IN VARCHAR2
    );
        
    PROCEDURE SP_GETEMPLEADO(
        REC_CURSOR   OUT SYS_REFCURSOR,
        PA_EMPLEADO  IN VARCHAR2
    );
END PA_COMPANIA;