CREATE OR REPLACE PACKAGE PA_EMPLEADOS AS
    
    PROCEDURE SP_GETEMPLEADO(
        REC_CURSOR OUT SYS_REFCURSOR
    );
    
    PROCEDURE SP_GETEMPLOYEE(
        REC_CURSOR   OUT SYS_REFCURSOR,
        PA_EMPLEADO  IN VARCHAR2
    );

    PROCEDURE SP_INSERT_EMPLEADOS(
        PA_TELEFONO  IN VARCHAR2,
        PA_APELLIDO  IN VARCHAR2,
        PA_NOMBRE    IN VARCHAR2,
        PA_SECCION   IN VARCHAR2,
        PA_SUELDO    IN VARCHAR2
    );

    PROCEDURE SP_UPDATE_EMPLEADO(
        PA_ID      IN VARCHAR2,
        PA_SECCION IN VARCHAR2,
        PA_SUELDO  IN VARCHAR2
    );

    PROCEDURE SP_DEDUCCIONES(
        REC_CURSOR   OUT SYS_REFCURSOR,
        PA_EMPLEADO  IN VARCHAR2
    );

    PROCEDURE SP_IMPUESTOS(
        REC_CURSOR   OUT SYS_REFCURSOR,
        PA_EMPLEADO  IN VARCHAR2
    );

END PA_EMPLEADOS;