CREATE OR REPLACE PACKAGE PA_USUARIOS AS
    
    PROCEDURE SP_GETUSUARIOS(
        REC_CURSOR OUT SYS_REFCURSOR
    );

    PROCEDURE SP_SETUSUARIO(
        PA_USER      IN  VARCHAR,
        PA_PASSWORD  IN  VARCHAR,
        PA_ROL       IN  VARCHAR
    );
    
    PROCEDURE SP_UPTUSUARIO(
        PA_ID        IN  VARCHAR,
        PA_USER      IN  VARCHAR,
        PA_PASSWORD  IN  VARCHAR,
        PA_ROL       IN  VARCHAR
    );

    PROCEDURE SP_GETUSUARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_USER IN VARCHAR
    );
    
    PROCEDURE SP_DELUSUARIO(        
        PA_USER IN VARCHAR
    );

END PA_USUARIOS;