CREATE OR REPLACE PACKAGE BODY PA_USUARIOS AS
    
    PROCEDURE SP_SETUSUARIO(
        PA_USER      IN  VARCHAR,
        PA_PASSWORD  IN  VARCHAR,
        PA_ROL       IN  VARCHAR
    )AS
    BEGIN
        IF TRIM(PA_USER) IS NULL OR TRIM(PA_PASSWORD) IS NULL OR
        PA_ROL IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSE
            INSERT INTO TA_USUARIOS (USUARIO, CONTRASENA, ROL) VALUES 
            (PA_USER, PA_PASSWORD, PA_ROL);
        END IF;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL USUARIO YA EXISTE');
            
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_SETUSUARIO: ' || SQLERRM);
    END SP_SETUSUARIO;

    PROCEDURE SP_GETUSUARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_USER IN VARCHAR
    )AS
        v_dummy  NUMBER;
    BEGIN
        SELECT 1
        INTO v_dummy
        FROM TA_USUARIOS
        WHERE UPPER(USUARIO)=UPPER(PA_USER)
        AND ROWNUM = 1;
        
        IF TRIM(PA_USER) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSE
            OPEN REC_CURSOR FOR
                SELECT * FROM TA_USUARIOS
                WHERE UPPER(USUARIO)=UPPER(PA_USER);
        END IF;
        
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'NO HAY DATOS DISPONIBLES SOBRE EL USUARIO');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_GETUSUARIO: ' || SQLERRM);
    END SP_GETUSUARIO;
END PA_USUARIOS;