CREATE OR REPLACE PACKAGE BODY PA_USUARIOS AS
    
    PROCEDURE SP_GETUSUARIOS(
        REC_CURSOR OUT SYS_REFCURSOR
    )AS
        v_dummy NUMBER;
    BEGIN
        SELECT 1
        INTO v_dummy
        FROM TA_USUARIOS
        WHERE ROWNUM = 1;
    
        OPEN REC_CURSOR FOR
            SELECT * FROM TA_USUARIOS
            ORDER BY ID_USUARIO;
            
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'NO HAY USUARIOS DISPONIBLES');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20099, 'ERROR INESPERADO: ' || SQLERRM);
    
    END SP_GETUSUARIOS;
    
    PROCEDURE SP_SETUSUARIO(
        PA_USER      IN  VARCHAR,
        PA_PASSWORD  IN  VARCHAR,
        PA_ROL       IN  VARCHAR
    )AS
    BEGIN
        IF TRIM(PA_USER) IS NULL OR TRIM(PA_PASSWORD) IS NULL OR
        TRIM(PA_ROL) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSE
            INSERT INTO TA_USUARIOS (USUARIO, CONTRASENA, ROL) VALUES 
            (PA_USER, PA_PASSWORD, PA_ROL);
        END IF;
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL USUARIO YA EXISTE');
            
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_SETUSUARIO: ' || SQLERRM);
    END SP_SETUSUARIO;

    PROCEDURE SP_UPTUSUARIO(
        PA_ID        IN  VARCHAR,
        PA_USER      IN  VARCHAR,
        PA_PASSWORD  IN  VARCHAR,
        PA_ROL       IN  VARCHAR
    )AS
        v_id NUMBER;
    BEGIN
        IF TRIM(PA_ID) IS NULL OR TRIM(PA_USER) IS NULL OR TRIM(PA_PASSWORD) IS NULL OR
        TRIM(PA_ROL) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSIF NOT REGEXP_LIKE(PA_ID, '^[0-9]+$') THEN
            RAISE_APPLICATION_ERROR(-20001, 'EL ID TIENE QUE SER NUMERICO');
        ELSE
            v_id := TO_NUMBER(PA_ID);
            UPDATE TA_USUARIOS SET USUARIO=PA_USER, CONTRASENA=PA_PASSWORD, ROL=PA_ROL
            WHERE ID_USUARIO = v_id;
        END IF;    
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL USUARIO YA EXISTE');
            
        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_UPTUSUARIO: ' || SQLERRM);
    END SP_UPTUSUARIO;

    PROCEDURE SP_GETUSUARIO(
        REC_CURSOR OUT SYS_REFCURSOR,
        PA_USER IN VARCHAR
    )AS
        v_dummy  NUMBER;
    BEGIN
        SELECT 1
        INTO v_dummy
        FROM TA_USUARIOS
        WHERE UPPER(USUARIO)=UPPER(PA_USER)
        AND ROWNUM = 1;
        
        IF TRIM(PA_USER) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSE
            OPEN REC_CURSOR FOR
                SELECT * FROM TA_USUARIOS
                WHERE UPPER(USUARIO)=UPPER(PA_USER);
        END IF;        
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'NO HAY DATOS DISPONIBLES SOBRE EL USUARIO');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_GETUSUARIO: ' || SQLERRM);
    END SP_GETUSUARIO;
    
    PROCEDURE SP_DELUSUARIO(
        PA_USER IN VARCHAR
    )AS
        v_dummy  NUMBER;
    BEGIN
        SELECT 1
        INTO v_dummy
        FROM TA_USUARIOS
        WHERE UPPER(USUARIO)=UPPER(PA_USER)
        AND ROWNUM = 1;
        
        IF TRIM(PA_USER) IS NULL THEN
            RAISE_APPLICATION_ERROR(-20000, 'NO SE PERMITEN ESPACIOS VACIOS');
        ELSE            
            DELETE FROM TA_USUARIOS WHERE UPPER(USUARIO)=UPPER(PA_USER);
        END IF;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RAISE_APPLICATION_ERROR(-20002, 'NO HAY DATOS DISPONIBLES SOBRE EL USUARIO');

        WHEN OTHERS THEN
            RAISE_APPLICATION_ERROR(-20002, 'ERROR EN SP_GETUSUARIO: ' || SQLERRM);
    END SP_DELUSUARIO;
END PA_USUARIOS;