CREATE OR REPLACE PROCEDURE SP_BORRADO_UNIVERSAL(
    PA_EMPLEADO IN VARCHAR
)AS
    v_empleado NUMBER;
    v_dummy NUMBER;
BEGIN
    IF TRIM(PA_EMPLEADO) IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN DATOS VACIOS');
    ELSIF NOT REGEXP_LIKE(PA_EMPLEADO, '^[0-9]+$') THEN
        RAISE_APPLICATION_ERROR(-20002, 'EL NUMERO DE EMPLEADO TIENE QUE SER NUMERICO');
    ELSE
        v_empleado := TO_NUMBER(PA_EMPLEADO);
        SELECT 1
        INTO v_dummy
        FROM TA_COMPANIA
        WHERE NUM_EMPLEADO = v_empleado
        AND ROWNUM = 1;

        SELECT 1
        INTO v_dummy
        FROM TA_DOCUMENTO
        WHERE NUM_EMPLEADO = v_empleado
        AND ROWNUM = 1;

        SELECT 1
        INTO v_dummy
        FROM TA_EMPLEADO
        WHERE NUM_EMPLEADO = v_empleado
        AND ROWNUM = 1;

        DELETE FROM TA_COMPANIA WHERE NUM_EMPLEADO = v_empleado;
        DELETE FROM TA_DOCUMENTO WHERE NUM_EMPLEADO = v_empleado;
        DELETE FROM TA_EMPLEADO WHERE NUM_EMPLEADO = v_empleado;
        DBMS_OUTPUT.PUT_LINE('DATOS ELIMINADOS EXITOSOMENTE');
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20003, 'NO HAY DATOS DISPONIBLES');

    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20099, 'ERROR INESPERADO: ' || SQLERRM);
END SP_BORRADO_UNIVERSAL;