CREATE OR REPLACE PROCEDURE SP_UNIVERSAL(
    PA_NOMBRE   IN VARCHAR2,
    PA_APELLIDO IN VARCHAR2,
    PA_EMPLEADO IN VARCHAR2
)AS
    BEGIN
    IF PA_NOMBRE IS NULL OR PA_APELLIDO IS NULL OR PA_EMPLEADO IS NULL THEN
        RAISE_APPLICATION_ERROR(-20001, 'NO SE PERMITEN REGISTROS VACÍOS');
    ELSIF NOT REGEXP_LIKE(PA_EMPLEADO, '^[0-9]+$') THEN
        RAISE_APPLICATION_ERROR(-20001, 'EL NUMERO DE EMPLEADO TIENE QUE SER NUMERICO');
    ELSE
        INSERT INTO TA_EMPLEADO (APELLIDO, NOMBRE, NUM_EMPLEADO) VALUES (PA_APELLIDO, PA_NOMBRE, PA_EMPLEADO);
        INSERT INTO TA_COMPANIA (APELLIDO, NOMBRE, NUM_EMPLEADO) VALUES (PA_APELLIDO, PA_NOMBRE, PA_EMPLEADO);
        INSERT INTO TA_DOCUMENTO (APELLIDO, NOMBRE, NUM_EMPLEADO) VALUES (PA_APELLIDO, PA_NOMBRE, PA_EMPLEADO);
    END IF;
    
    EXCEPTION
        WHEN DUP_VAL_ON_INDEX THEN
            RAISE_APPLICATION_ERROR(-20003, 'EL NUMERO DE EMPLEADO YA EXISTE');
END SP_UNIVERSAL;